version: "3.0"
services:

  mysql:
    image: mysql:8
    container_name: fingerprint-auth-mysql
    working_dir: /application
    volumes:
      - .:/application
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=fingerprint-auth
      - MYSQL_USER=Test
      - MYSQL_PASSWORD=Test1234
    ports:
      - "8020:3306"

  adminer:
    image: adminer
    container_name: fingerprint-auth-adminer
    ports:
      - "8091:8080"
    networks:
      - default

  webserver:
    build: docker/nginx
    container_name: fingeprint-auth-webserver
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8021:80"
    networks:
      - default

  php-fpm:
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    container_name: fingerprint-auth
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini

  mailhog:
    image: mailhog/mailhog
    container_name: fingerprint-auth-mailhog
    ports:
      - "8024:8025"
      - "1013:1025"

networks:
  default:
    driver: bridge
