version: "3.0"
services:

  mysql:
    image: mysql:8
    container_name: tours-mysql
    working_dir: /application
    volumes:
      - .:/application
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=tours
      - MYSQL_USER=Test
      - MYSQL_PASSWORD=Test1234
    ports:
      - "8028:3306"

  adminer:
    image: adminer
    container_name: tours-adminer
    ports:
      - "8098:8080"
    networks:
      - default

  webserver:
    build: docker/nginx
    container_name: tours-webserver
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8029:80"
    networks:
      - default

  php-fpm:
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    container_name: tours
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini

  mailhog:
    image: mailhog/mailhog
    container_name: tours-mailhog
    ports:
      - "8030:8025"
      - "1013:1025"

networks:
  default:
    driver: bridge
